name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: codfish/semantic-release-action@v3
        id: semantic
        with:
          additional-packages: semantic-release-gitmoji
          plugins: |
            [
              'semantic-release-gitmoji',
              '@semantic-release/release-notes-generator',
              '@semantic-release/github'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}